name: doxygen

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: Install Tools
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -qq install doxygen graphviz

      - name: generat doxygen html
        shell: bash
        run: |
          ls
          cd doc/doxygen
          doxygen Doxyfile

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: gh-pages
          folder: doc/doxygen/output
